# Generated by Django 4.1.6 on 2023-08-29 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0011_psicologo_user'),
        ('paciente', '0003_alter_paciente_amaterno_alter_paciente_apaterno_and_more'),
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo', verbose_name='Psicologo'),
            preserve_default=False,
        ),
    ]
