# Generated by Django 4.1.6 on 2023-09-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_fecha_cita_cita_paciente_cita_psicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(verbose_name='Fecha de cita'),
        ),
    ]
