# Generated by Django 4.1.6 on 2023-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apaterno', models.CharField(max_length=120)),
                ('amaterno', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('especialidad', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='psicologos/')),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
