# Generated by Django 4.1.6 on 2023-08-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados_psicologos/'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='psicologos_foto_perfil/'),
        ),
    ]
