# Generated by Django 4.1.6 on 2023-08-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0002_alter_psicologo_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='amaterno',
            field=models.CharField(max_length=120, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='apaterno',
            field=models.CharField(max_length=120, verbose_name='Primer Apellido'),
        ),
    ]
