# Generated by Django 4.1.6 on 2023-08-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0003_alter_psicologo_amaterno_alter_psicologo_apaterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='especialidad',
            field=models.CharField(choices=[('clinica', 'Psicología Clínica'), ('educativa', 'Psicología Educativa'), ('deporte', 'Psicología del Deporte'), ('organizacional', 'Psicología Organizacional'), ('forense', 'Psicología Forense'), ('salud_mental', 'Salud Mental'), ('terapia_familiar', 'Terapia Familiar'), ('neuropsicologia', 'Neuropsicología'), ('psicologia_infantil', 'Psicología Infantil'), ('psicoterapia', 'Psicoterapia'), ('psicologia_social', 'Psicología Social'), ('gerontologia', 'Gerontología'), ('psicologia_rehabilitacion', 'Psicología de la Rehabilitación'), ('psicologia_educacional', 'Psicología Educacional'), ('psicologia_legal', 'Psicología Legal'), ('orientacion_vocacional', 'Orientación Vocacional'), ('terapia_sexual', 'Terapia Sexual'), ('terapia_pareja', 'Terapia de Pareja'), ('psicologia_transpersonal', 'Psicología Transpersonal')], max_length=100),
        ),
    ]
