# Generated by Django 4.1.6 on 2023-08-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0005_rename_certificado_pdf_psicologo_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo', verbose_name='Psicologo'),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='servicios_ofrecidos',
            field=models.TextField(blank=True),
        ),
    ]
