# Generated by Django 4.1.6 on 2023-08-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0006_consultorio_direccion_consultorio_horario_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='psicologo',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='consultorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologo.consultorio', verbose_name='Consultorio'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='identificacion_oficial',
            field=models.FileField(blank=True, null=True, upload_to='identificacion_psicologos/'),
        ),
    ]
