# Generated by Django 4.1.6 on 2023-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0008_psicologo_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
