<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-08-29 03:37
=======
# Generated by Django 4.1.6 on 2023-08-29 04:49
>>>>>>> 4aeac88ec6e23f16f9abd7dc129d1183db4384a1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0009_remove_psicologo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='anio_obtencion',
            field=models.PositiveIntegerField(null=True, verbose_name='Año de obtención'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='institucion_otorgamiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de otorgamiento'),
        ),
    ]
