# Generated by Django 4.1.6 on 2023-08-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0009_remove_psicologo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='anio_obtencion',
            field=models.PositiveIntegerField(null=True, verbose_name='Año de obtención'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='institucion_otorgamiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de otorgamiento'),
        ),
    ]
