# Generated by Django 4.1.6 on 2023-08-29 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psicologo', '0010_alter_psicologo_anio_obtencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
