# Generated by Django 3.2.21 on 2023-09-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0010_alter_psicologo_anio_obtencion_and_more'),
        ('psicologo', '0010_auto_20230903_2017'),
    ]

    operations = [
    ]
