# Generated by Django 4.1.6 on 2023-09-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0011_psicologo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='amaterno',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='apaterno',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='enlace_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='enlace_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='enlace_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='enlace_pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
