# Generated by Django 4.1.6 on 2023-09-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0014_alter_psicologo_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='consultorio',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo', verbose_name='Consultorio'),
        ),
    ]
