# Generated by Django 3.2.21 on 2023-09-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0010_auto_20230903_2017'),
        ('psicologo', '0015_remove_psicologo_consultorio_consultorio_psicologo'),
    ]

    operations = [
    ]
