# Generated by Django 3.2.21 on 2023-09-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0011_merge_20230905_0348'),
        ('psicologo', '0016_merge_20230905_1835'),
        ('psicologo', '0016_merge_20230905_2137'),
    ]

    operations = [
    ]
