# Generated by Django 3.2.21 on 2023-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0017_merge_20230906_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='servicios_ofrecidos',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='horario_atencion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='especialidad',
            field=models.CharField(choices=[('clinica', 'Psicología Clínica'), ('educativa', 'Psicología Educativa'), ('deporte', 'Psicología del Deporte'), ('organizacional', 'Psicología Organizacional'), ('forense', 'Psicología Forense'), ('salud_mental', 'Salud Mental'), ('terapia_familiar', 'Terapia Familiar'), ('neuropsicologia', 'Neuropsicología'), ('psicologia_infantil', 'Psicología Infantil'), ('psicoterapia', 'Psicoterapia'), ('psicologia_social', 'Psicología Social'), ('gerontologia', 'Gerontología'), ('psicologia_rehabilitacion', 'Psicología de la Rehabilitación'), ('psicologia_educacional', 'Psicología Educacional'), ('psicologia_legal', 'Psicología Legal'), ('orientacion_vocacional', 'Orientación Vocacional'), ('terapia_sexual', 'Terapia Sexual'), ('terapia_pareja', 'Terapia de Pareja'), ('psicologia_transpersonal', 'Psicología Transpersonal'), ('otra_especialidad', 'Otra Especialidad')], max_length=100),
        ),
    ]
