# Generated by Django 3.2.21 on 2023-09-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0018_auto_20230928_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
    ]
