# Generated by Django 3.2.21 on 2023-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0019_alter_psicologo_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
