# Generated by Django 3.2.21 on 2023-10-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0020_alter_psicologo_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='especialidad',
            field=models.CharField(max_length=200, verbose_name='Especialidad'),
        ),
    ]
