# Generated by Django 3.2.22 on 2023-10-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0021_alter_psicologo_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='direccion',
            field=models.CharField(max_length=250, verbose_name='Dirección'),
        ),
    ]
