# Generated by Django 3.2.22 on 2023-10-19 03:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0022_alter_consultorio_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='diario',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
