# Generated by Django 3.2.22 on 2023-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0023_psicologo_diario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psicologo',
            old_name='diario',
            new_name='diario_personal',
        ),
    ]
