# Generated by Django 4.1.6 on 2023-08-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='amaterno',
            field=models.CharField(max_length=120, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apaterno',
            field=models.CharField(max_length=120, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(max_length=100, verbose_name='Ocupación'),
        ),
    ]
