# Generated by Django 4.1.6 on 2023-09-05 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0003_alter_paciente_amaterno_alter_paciente_apaterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='amaterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apaterno',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
