# Generated by Django 3.2.21 on 2023-09-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0017_merge_20230906_2038'),
        ('paciente', '0004_remove_paciente_amaterno_remove_paciente_apaterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expediente',
            old_name='antecedentes_medicos',
            new_name='notas_compartidas',
        ),
        migrations.RenameField(
            model_name='expediente',
            old_name='diagnostico',
            new_name='notas_personales',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='expediente',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo'),
            preserve_default=False,
        ),
    ]
