# Generated by Django 3.2.23 on 2023-12-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20230908_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=254, verbose_name='Descripción'),
        ),
    ]
