# Generated by Django 3.2.23 on 2023-12-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='pacientes_foto_perfil/'),
        ),
    ]
